### ISSUE TITLE
Not found error

### ISSUE THREAD

**Issue by yceballost** [mikaelvesavuori/figma-plugin-continuous-design#1]
Hello !

Thanks for this plugin!

This error message appear when I try to connect Plugin with Github

```
{
"message": "Not Found",
"documentation_url": "https://docs.github.com/rest"
}
```

The repository is in a Organization (if helps)
![image](https://user-images.githubusercontent.com/6722153/142276712-e57fd61c-5cd7-4138-a59d-d4d4d0e56e4c.png)

Regards!!

**Comment by erisvaldojunior** [comment]
@yceballost make sure to enable workflows on your Github repo -> Actions tab before pressing Start CI workflow.

**Comment by yceballost** [comment]
I did it.

Actions through an error
`Error: Error: Error: Missing one or more of required arguments: "figmaToken", "figmaUrl" when attempting to get data from Figma API!` 

But I have my secrets corretly created.
FIGMA_URL: with my document ID
FIGMA_TOKEN: with my figma personal access token made it from profile > configuration

**Comment by mikaelvesavuori** [comment]
That would be a Figmagic issue, and not one strictly related to this plugin.
